// AUTO-GENERATED by scripts/codegen.ts from `orcr api schema`. DO NOT EDIT.
// Every socket method is covered here 1:1 (spec §8). Regenerate with `npm run codegen`;
// `npm run codegen:check` fails the build if this file drifts from the live schema.

import type { Transport, Subscription } from "./wire.js";

/** Every socket method name (sorted; the parity source of truth). */
export const PROTOCOL_METHODS = [
  "agent.ask",
  "agent.attach.heartbeat",
  "agent.attach.prepare",
  "agent.attach.release",
  "agent.kill",
  "agent.logs",
  "agent.ls",
  "agent.run",
  "agent.send",
  "agent.wait",
  "api.schema",
  "api.snapshot",
  "events.subscribe",
  "loop.create",
  "loop.logs",
  "loop.ls",
  "loop.pause",
  "loop.resume",
  "loop.rm",
  "loop.run.ls",
  "loop.run.start",
  "loop.run.stop",
  "server.handshake",
  "server.status",
  "server.stop",
  "watch.open"
] as const;

/** Streaming (subscription) methods. */
export const STREAMING_METHODS = [
  "events.subscribe",
  "watch.open"
] as const;

/** The event kinds a subscriber may receive (spec §11.6). */
export const EVENT_KINDS = [
  "agent.created",
  "agent.ended",
  "agent.location_changed",
  "agent.response_captured",
  "agent.status_changed",
  "agent.turn_completed",
  "attach.ended",
  "attach.started",
  "loop.coalesced",
  "loop.created",
  "loop.ended",
  "loop.fired",
  "loop.paused",
  "loop.removed",
  "loop.resumed",
  "loop.skipped",
  "loop_run.ended",
  "loop_run.started",
  "loop_run.stopping",
  "queue.promoted",
  "server_stopping"
] as const;

/** The stable §13 error codes with exit mappings. */
export const ERROR_CODES = [
  {
    "code": "not_found",
    "exit": 6
  },
  {
    "code": "invalid_request",
    "exit": 1
  },
  {
    "code": "state_conflict",
    "exit": 7
  },
  {
    "code": "blocked",
    "exit": 4
  },
  {
    "code": "timeout",
    "exit": 3
  },
  {
    "code": "integration_missing",
    "exit": 2
  },
  {
    "code": "transcript_unavailable",
    "exit": 1
  },
  {
    "code": "environment_error",
    "exit": 2
  },
  {
    "code": "server_error",
    "exit": 1
  }
] as const;

export interface AgentAskParams {
  agent?: string;
  caller_id?: string;
  caller_path?: string;
  cwd?: string;
  effort?: string;
  model?: string;
  name?: string;
  path?: string;
  prompt?: string;
  timeout?: string;
  [key: string]: unknown;
}

export interface AgentAskResult {
  path?: string;
  response?: Record<string, unknown>;
  uuid?: string;
  [key: string]: unknown;
}

export interface AgentAttachHeartbeatParams {
  lease_id?: string;
  [key: string]: unknown;
}

export interface AgentAttachHeartbeatResult {
  ok?: boolean;
  [key: string]: unknown;
}

export interface AgentAttachPrepareParams {
  caller_id?: string;
  caller_path?: string;
  client_pid?: number;
  takeover?: boolean;
  target?: string;
  [key: string]: unknown;
}

export interface AgentAttachPrepareResult {
  command?: string[];
  lease_id?: string;
  path?: string;
  takeover?: boolean;
  ttl_ms?: number;
  uuid?: string;
  [key: string]: unknown;
}

export interface AgentAttachReleaseParams {
  lease_id?: string;
  [key: string]: unknown;
}

export interface AgentAttachReleaseResult {
  released?: boolean;
  [key: string]: unknown;
}

export interface AgentKillParams {
  caller_id?: string;
  caller_path?: string;
  force?: boolean;
  preview?: boolean;
  targets?: string[];
  [key: string]: unknown;
}

export interface AgentKillResult {
  all_killed?: boolean;
  killed?: Record<string, unknown>[];
  skipped?: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface AgentLogsParams {
  caller_id?: string;
  caller_path?: string;
  follow?: boolean;
  last_response?: boolean;
  tail?: number;
  target?: string;
  [key: string]: unknown;
}

export interface AgentLogsResult {
  entries?: Record<string, unknown>[];
  path?: string;
  resolved?: string;
  response?: Record<string, unknown>;
  uuid?: string;
  [key: string]: unknown;
}

export interface AgentLsParams {
  agent?: string;
  all?: boolean;
  caller_id?: string;
  caller_path?: string;
  managed?: boolean;
  pattern?: string;
  status?: string;
  unmanaged?: boolean;
  [key: string]: unknown;
}

export interface AgentLsResult {
  agents?: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface AgentRunParams {
  agent?: string;
  caller_id?: string;
  caller_path?: string;
  cwd?: string;
  effort?: string;
  gc?: string;
  model?: string;
  name?: string;
  path?: string;
  prompt?: string;
  timeout?: string;
  [key: string]: unknown;
}

export interface AgentRunResult {
  agent?: Record<string, unknown>;
  permissions?: string;
  [key: string]: unknown;
}

export interface AgentSendParams {
  caller_id?: string;
  caller_path?: string;
  prompt?: string;
  target?: string;
  [key: string]: unknown;
}

export interface AgentSendResult {
  delivered_while?: string;
  input_seq?: number;
  path?: string;
  uuid?: string;
  [key: string]: unknown;
}

export interface AgentWaitParams {
  caller_id?: string;
  caller_path?: string;
  targets?: string[];
  timeout?: string;
  [key: string]: unknown;
}

export interface AgentWaitResult {
  all_ok?: boolean;
  decision_seq?: number;
  targets?: Record<string, unknown>[];
  timed_out?: boolean;
  [key: string]: unknown;
}

export interface ApiSchemaParams { [key: string]: unknown; }

export interface ApiSchemaResult { [key: string]: unknown; }

export interface ApiSnapshotParams { [key: string]: unknown; }

export interface ApiSnapshotResult {
  agents?: Record<string, unknown>[];
  loops?: Record<string, unknown>[];
  queue?: Record<string, unknown>[];
  snapshot_seq?: number;
  [key: string]: unknown;
}

export interface EventsSubscribeParams {
  since_seq?: number;
  [key: string]: unknown;
}

export interface LoopCreateParams {
  command?: string[];
  cron?: string;
  cwd?: string;
  max_concurrency?: number;
  name?: string;
  once_at?: string;
  overlap?: string;
  timeout?: string;
  [key: string]: unknown;
}

export interface LoopCreateResult {
  loop?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface LoopLogsParams {
  follow?: boolean;
  name?: string;
  run?: string;
  source?: string;
  tail?: number;
  [key: string]: unknown;
}

export interface LoopLogsResult {
  lines?: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface LoopLsParams {
  all?: boolean;
  names?: string[];
  status?: string;
  [key: string]: unknown;
}

export interface LoopLsResult {
  loops?: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface LoopPauseParams {
  names?: string[];
  [key: string]: unknown;
}

export interface LoopPauseResult { [key: string]: unknown; }

export interface LoopResumeParams {
  names?: string[];
  [key: string]: unknown;
}

export interface LoopResumeResult { [key: string]: unknown; }

export interface LoopRmParams {
  caller_id?: string;
  caller_path?: string;
  kill_active?: boolean;
  names?: string[];
  [key: string]: unknown;
}

export interface LoopRmResult { [key: string]: unknown; }

export interface LoopRunLsParams {
  all?: boolean;
  name?: string;
  status?: string;
  [key: string]: unknown;
}

export interface LoopRunLsResult {
  runs?: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface LoopRunStartParams {
  name?: string;
  [key: string]: unknown;
}

export interface LoopRunStartResult {
  run?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface LoopRunStopParams {
  name?: string;
  run?: string;
  [key: string]: unknown;
}

export interface LoopRunStopResult {
  skipped?: Record<string, unknown>[];
  stopped?: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface ServerHandshakeParams { [key: string]: unknown; }

export interface ServerHandshakeResult {
  pid?: number;
  protocol?: number;
  ready?: boolean;
  store?: string;
  [key: string]: unknown;
}

export interface ServerStatusParams { [key: string]: unknown; }

export interface ServerStatusResult {
  counts?: Record<string, unknown>;
  drift?: Record<string, unknown>;
  herdr?: Record<string, unknown>;
  integrations?: Record<string, unknown>;
  loops?: Record<string, unknown>[];
  loops_firing?: boolean;
  protocol?: number;
  socket?: string;
  store?: string;
  version?: string;
  [key: string]: unknown;
}

export interface ServerStopParams { [key: string]: unknown; }

export interface ServerStopResult {
  status?: string;
  [key: string]: unknown;
}

export interface WatchOpenParams { [key: string]: unknown; }

/**
 * The generated protocol client: every socket method, 1:1. The convenience helpers in
 * `client.ts` are built on top of this — anything the SDK does, this client can do directly.
 */
export class GeneratedClient {
  constructor(protected readonly transport: Transport) {}

  /** Escape hatch: call any protocol method by name (used by generic helpers). */
  call(method: (typeof PROTOCOL_METHODS)[number], params: unknown = {}): Promise<unknown> {
    return this.transport.request(method, params);
  }

  /** `agent.ask` — run --gc immediate → wait → last response, in one call. */
  async agentAsk(params: AgentAskParams = {}): Promise<AgentAskResult> {
    return (await this.transport.request("agent.ask", params)) as AgentAskResult;
  }

  /** `agent.attach.heartbeat` — Refresh an attach lease so GC keeps deferring while the terminal is attached. */
  async agentAttachHeartbeat(params: AgentAttachHeartbeatParams = {}): Promise<AgentAttachHeartbeatResult> {
    return (await this.transport.request("agent.attach.heartbeat", params)) as AgentAttachHeartbeatResult;
  }

  /** `agent.attach.prepare` — Insert an attach lease and return the herdr attach exec command. */
  async agentAttachPrepare(params: AgentAttachPrepareParams = {}): Promise<AgentAttachPrepareResult> {
    return (await this.transport.request("agent.attach.prepare", params)) as AgentAttachPrepareResult;
  }

  /** `agent.attach.release` — Release an attach lease on detach (GC resumes). */
  async agentAttachRelease(params: AgentAttachReleaseParams = {}): Promise<AgentAttachReleaseResult> {
    return (await this.transport.request("agent.attach.release", params)) as AgentAttachReleaseResult;
  }

  /** `agent.kill` — Kill matched agents (graceful per-integration shutdown; panes closed). */
  async agentKill(params: AgentKillParams = {}): Promise<AgentKillResult> {
    return (await this.transport.request("agent.kill", params)) as AgentKillResult;
  }

  /** `agent.logs` — Read an agent's native transcript (optionally only the last response). */
  async agentLogs(params: AgentLogsParams = {}): Promise<AgentLogsResult> {
    return (await this.transport.request("agent.logs", params)) as AgentLogsResult;
  }

  /** `agent.ls` — List active (and, with all, ended) agents as flat rows. */
  async agentLs(params: AgentLsParams = {}): Promise<AgentLsResult> {
    return (await this.transport.request("agent.ls", params)) as AgentLsResult;
  }

  /** `agent.run` — Enqueue a new managed agent; returns its path + uuid. */
  async agentRun(params: AgentRunParams = {}): Promise<AgentRunResult> {
    return (await this.transport.request("agent.run", params)) as AgentRunResult;
  }

  /** `agent.send` — Deliver a prompt to an existing agent's TUI. */
  async agentSend(params: AgentSendParams = {}): Promise<AgentSendResult> {
    return (await this.transport.request("agent.send", params)) as AgentSendResult;
  }

  /** `agent.wait` — Block until every target agent settles. */
  async agentWait(params: AgentWaitParams = {}): Promise<AgentWaitResult> {
    return (await this.transport.request("agent.wait", params)) as AgentWaitResult;
  }

  /** `api.schema` — The versioned JSON Schema of the whole socket protocol. */
  async apiSchema(params: ApiSchemaParams = {}): Promise<ApiSchemaResult> {
    return (await this.transport.request("api.schema", params)) as ApiSchemaResult;
  }

  /** `api.snapshot` — One consistent runtime-state document stamped with snapshot_seq. */
  async apiSnapshot(params: ApiSnapshotParams = {}): Promise<ApiSnapshotResult> {
    return (await this.transport.request("api.snapshot", params)) as ApiSnapshotResult;
  }

  /** `events.subscribe` — Subscribe to the event stream from since_seq; replay then live. Streams event frames. */
  eventsSubscribe(params: EventsSubscribeParams = {}): Promise<Subscription> {
    return this.transport.openStream("events.subscribe", params);
  }

  /** `loop.create` — Create a durable cron loop over an argv command. */
  async loopCreate(params: LoopCreateParams = {}): Promise<LoopCreateResult> {
    return (await this.transport.request("loop.create", params)) as LoopCreateResult;
  }

  /** `loop.logs` — Interleaved loop command output + scheduler actions. */
  async loopLogs(params: LoopLogsParams = {}): Promise<LoopLogsResult> {
    return (await this.transport.request("loop.logs", params)) as LoopLogsResult;
  }

  /** `loop.ls` — List loops. */
  async loopLs(params: LoopLsParams = {}): Promise<LoopLsResult> {
    return (await this.transport.request("loop.ls", params)) as LoopLsResult;
  }

  /** `loop.pause` — Pause loop(s): no new fires. */
  async loopPause(params: LoopPauseParams = {}): Promise<LoopPauseResult> {
    return (await this.transport.request("loop.pause", params)) as LoopPauseResult;
  }

  /** `loop.resume` — Resume paused loop(s). */
  async loopResume(params: LoopResumeParams = {}): Promise<LoopResumeResult> {
    return (await this.transport.request("loop.resume", params)) as LoopResumeResult;
  }

  /** `loop.rm` — Remove loop(s); optionally kill active runs. */
  async loopRm(params: LoopRmParams = {}): Promise<LoopRmResult> {
    return (await this.transport.request("loop.rm", params)) as LoopRmResult;
  }

  /** `loop.run.ls` — List a loop's runs. */
  async loopRunLs(params: LoopRunLsParams = {}): Promise<LoopRunLsResult> {
    return (await this.transport.request("loop.run.ls", params)) as LoopRunLsResult;
  }

  /** `loop.run.start` — Manually trigger a loop run. */
  async loopRunStart(params: LoopRunStartParams = {}): Promise<LoopRunStartResult> {
    return (await this.transport.request("loop.run.start", params)) as LoopRunStartResult;
  }

  /** `loop.run.stop` — Stop run(s) of a loop without touching the definition. */
  async loopRunStop(params: LoopRunStopParams = {}): Promise<LoopRunStopResult> {
    return (await this.transport.request("loop.run.stop", params)) as LoopRunStopResult;
  }

  /** `server.handshake` — Readiness probe: returns pid, protocol, and store path. */
  async serverHandshake(params: ServerHandshakeParams = {}): Promise<ServerHandshakeResult> {
    return (await this.transport.request("server.handshake", params)) as ServerHandshakeResult;
  }

  /** `server.status` — Server health: version, protocol, paths, herdr reachability, counts, integrations. */
  async serverStatus(params: ServerStatusParams = {}): Promise<ServerStatusResult> {
    return (await this.transport.request("server.status", params)) as ServerStatusResult;
  }

  /** `server.stop` — Graceful control-plane stop: stop accepting, close subscriptions, release socket. Never touches panes. */
  async serverStop(params: ServerStopParams = {}): Promise<ServerStopResult> {
    return (await this.transport.request("server.stop", params)) as ServerStopResult;
  }

  /** `watch.open` — Snapshot + subscription under one cursor pin (no re-snapshot livelock). Streams event frames. */
  watchOpen(params: WatchOpenParams = {}): Promise<Subscription> {
    return this.transport.openStream("watch.open", params);
  }
}
