// Codegen: generate `src/generated.ts` — the protocol client covering every socket method
// 1:1 — from `orcr api schema`. Run in CI (`npm run codegen:check`) so schema drift fails the
// build (regenerated in CI so drift fails the build). Usage:
//   tsx scripts/codegen.ts          # write src/generated.ts
//   tsx scripts/codegen.ts --check  # fail if src/generated.ts is out of date

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "..", "src", "generated.ts");

interface MethodSchema {
  summary: string;
  implemented: boolean;
  streaming: boolean;
  params: JsonSchema;
  result: JsonSchema;
}
interface JsonSchema {
  type?: string;
  properties?: Record<string, JsonSchema>;
  items?: JsonSchema;
}

function loadSchema(): { methods: Record<string, MethodSchema>; events: string[]; errorCodes: unknown } {
  const bin = process.env.ORCR_BIN && process.env.ORCR_BIN.length > 0 ? process.env.ORCR_BIN : "orcr";
  const raw = execFileSync(bin, ["api", "schema"], { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 });
  const doc = JSON.parse(raw);
  return {
    methods: doc.methods as Record<string, MethodSchema>,
    events: Object.keys(doc.events ?? {}).sort(),
    errorCodes: doc.errorCodes,
  };
}

/** dot-name → camelCase method name (`loop.run.start` → `loopRunStart`). */
function camel(name: string): string {
  const parts = name.split(/[._]/);
  return parts
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join("");
}

/** dot-name → PascalCase type prefix (`loop.run.start` → `LoopRunStart`). */
function pascal(name: string): string {
  const c = camel(name);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

function tsType(schema: JsonSchema | undefined): string {
  if (!schema) return "unknown";
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return `${tsType(schema.items)}[]`;
    case "object":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function emitInterface(typeName: string, schema: JsonSchema): string {
  const props = schema.properties ?? {};
  const keys = Object.keys(props).sort();
  if (keys.length === 0) {
    return `export interface ${typeName} { [key: string]: unknown; }`;
  }
  const lines = keys.map((k) => `  ${k}?: ${tsType(props[k])};`);
  return `export interface ${typeName} {\n${lines.join("\n")}\n  [key: string]: unknown;\n}`;
}

function generate(): string {
  const { methods, events, errorCodes } = loadSchema();
  const names = Object.keys(methods).sort(); // deterministic order (schema is key-sorted)

  const header = `// AUTO-GENERATED by scripts/codegen.ts from \`orcr api schema\`. DO NOT EDIT.
// Every socket method is covered here 1:1. Regenerate with \`npm run codegen\`;
// \`npm run codegen:check\` fails the build if this file drifts from the live schema.

import type { Transport, Subscription } from "./wire.js";

/** Every socket method name (sorted; the parity source of truth). */
export const PROTOCOL_METHODS = ${JSON.stringify(names, null, 2)} as const;

/** Streaming (subscription) methods. */
export const STREAMING_METHODS = ${JSON.stringify(
    names.filter((n) => methods[n].streaming),
    null,
    2,
  )} as const;

/** The event kinds a subscriber may receive. */
export const EVENT_KINDS = ${JSON.stringify(events, null, 2)} as const;

/** The stable error codes with exit mappings. */
export const ERROR_CODES = ${JSON.stringify(errorCodes, null, 2)} as const;
`;

  const interfaces: string[] = [];
  for (const name of names) {
    const p = pascal(name);
    interfaces.push(emitInterface(`${p}Params`, methods[name].params));
    if (!methods[name].streaming) {
      interfaces.push(emitInterface(`${p}Result`, methods[name].result));
    }
  }

  const clientMethods: string[] = [];
  for (const name of names) {
    const c = camel(name);
    const p = pascal(name);
    const m = methods[name];
    const doc = `  /** \`${name}\` — ${m.summary} */`;
    if (m.streaming) {
      clientMethods.push(
        `${doc}\n  ${c}(params: ${p}Params = {}): Promise<Subscription> {\n    return this.transport.openStream(${JSON.stringify(
          name,
        )}, params);\n  }`,
      );
    } else {
      clientMethods.push(
        `${doc}\n  async ${c}(params: ${p}Params = {}): Promise<${p}Result> {\n    return (await this.transport.request(${JSON.stringify(
          name,
        )}, params)) as ${p}Result;\n  }`,
      );
    }
  }

  const cls = `
/**
 * The generated protocol client: every socket method, 1:1. The convenience helpers in
 * \`client.ts\` are built on top of this — anything the SDK does, this client can do directly.
 */
export class GeneratedClient {
  constructor(protected readonly transport: Transport) {}

  /** Escape hatch: call any protocol method by name (used by generic helpers). */
  call(method: (typeof PROTOCOL_METHODS)[number], params: unknown = {}): Promise<unknown> {
    return this.transport.request(method, params);
  }

${clientMethods.join("\n\n")}
}
`;

  return `${header}\n${interfaces.join("\n\n")}\n${cls}`;
}

function main(): void {
  const check = process.argv.includes("--check");
  const generated = generate();
  if (check) {
    let current = "";
    try {
      current = readFileSync(OUT, "utf8");
    } catch {
      // missing → treated as drift
    }
    if (current.trim() !== generated.trim()) {
      console.error(
        "generated.ts is out of date with `orcr api schema`. Run `npm run codegen` and commit.",
      );
      process.exit(1);
    }
    console.log("generated.ts is up to date.");
    return;
  }
  writeFileSync(OUT, generated);
  console.log(`wrote ${OUT}`);
}

main();
